### ISSUE TITLE
High precipitation for October 23rd 2016

### ISSUE THREAD

**Issue by JensWahl** [metno/NWPdocs#11]
Hi, 

First of all, thank you for all of your great products! 

I'm downloading data from the MET post-processed products Rerun version 2 product for October 23rd, 2016 for Denmark. I find that some hours have precipitation that seems unreasonable high leading to daily precipitation above 400 mm (see the figure below for the sum of the hourly precipitation). 

![image](https://user-images.githubusercontent.com/25640115/152846797-d74bf809-e3ee-4448-be11-65b0cff04844.png)

If one looks at the hour to hour precipitation for the coordinate (in lambert conformal conic the coordinate is (-291442.2, -764322)) with the highest precipitation they seem to be just consistently high, no specific hour stands out. Do any of you know why one would observe such high values? 

![image](https://user-images.githubusercontent.com/25640115/152848551-ef197ad8-348b-4283-beb1-0bf17ed106e7.png)

Thanks! 

Jens

**Comment by cristianlussana** [comment]
Hi Jens,
Thanks for your feedback. We will report this in a new section "Know issues" on our wiki for the post-proc products. Most likely, the high amount of precipitation is due to some suspicious observations that have not been detected by our automatic data quality control procedures. We will try to remove them in the next version of the MET Nordic analysis archive.
Best regards,
Cristian
