### ISSUE TITLE
Finer gridded vertical cross section data

### ISSUE THREAD

**Issue by simeneide** [metno/NWPdocs#27]
First off all, thanks alot for providing the MEPS data free of charge. It has been a great playground for me lately :)

I am a enthusiastic paraglider pilot, and have developed a small service (see https://flysogn.streamlit.app/  and select "forecast") that shows wind and thermal activity forecasted by METS so that we can use it for planning and expectations. This seems to work quite well. 
![6d8329371f18c767b7dca7f2f00c0e3e06d2291c5e171bbe05795ea0](https://github.com/metno/NWPdocs/assets/7136076/23026962-c11a-4805-a715-167f84f654b0)

However, after some investigations, I have realized that you output a quite sparse grid in your `meps_lagged_6_h_vc_2_5km` and `meps_det_vc_2_5km` files.

![Screenshot 2024-05-01 at 12 27 40](https://github.com/metno/NWPdocs/assets/7136076/315a0669-d994-4118-b0db-0eec666f404f)

For example, in my local area (sogndal), the two closest points are 10 and 16 km away, respectively. This would of course be better if I got proper output of the 2.5km grid (I assume an interpolation here would not be as good).

Is there a possibility to add this as model outputs? Or am I thinking wrongly here? The way I load the forecast can be seen [here].(https://github.com/simeneide/flysogn/blob/main/meps.py#L21).

Secondly, is it possible to add lat lon dimensions to the dataset? The way I can filter down a position now is through the following code (which is slow):
```
    subset = dataset.where(
        (np.abs(dataset.latitude - lat) < tol) & (np.abs(dataset.longitude - lon) < tol), 
        drop=True
    )
```

**Comment by eivindsMET** [comment]
Hi Simen,
Cool website! Nice that you use our data :)
These vc-files you look at are actually used routinely by our forecasters,
and the point / cross section selection is very limited to the points of
interest that they need. We are not able to extend this list for general
users unfortunately, since the files and processing chain becomes too
demanding.
We would in fact encourage you to change and look at the full model output
files instead, e.g.
https://thredds.met.no/thredds/catalog/meps25epsarchive/2024/01/01/catalog.html
-> meps_det_ml_20240101T00Z.ncml
<https://thredds.met.no/thredds/catalog/meps25epsarchive/2024/01/01/catalog.html?dataset=meps25epsarchive/2024/01/01/meps_det_ml_20240101T00Z.ncml>
for
model level parameters, Here is information on the full model grid and all
vertical model levels.
Take a look at https://github.com/metno/NWPdocs/wiki/New-MEPS-Archive-2023
for an overview of which files are in the archive.

Good luck!

Eivind

ons. 1. mai 2024 kl. 12:36 skrev Simen ***@***.***>:

**Comment by simeneide** [comment]
Hi Eivind,
great! This was exactly the pointer I wanted, I was just looking in the wrong directories. The files you pointed me to seems to have exactly what I want :)

One problem I have, is that the files seems to be overly slow to download/use. For example, even after downsampling to only a 32mb dataset like in the code below, it takes over 30 minutes to run the `subset.load()` command. And not loading ensures that everything else takes forever. Might be more of an xarray thing, but any tips? Or could it be that your servers are slower than xarray expects in some way?


```
import xarray as xr
from siphon.catalog import TDSCatalog
import numpy as np
import streamlit as st
import datetime
from datetime import datetime
from siphon.catalog import TDSCatalog


# %%

def find_latest_meps_file():
    today = datetime.today()
    catalog_url = f"https://thredds.met.no/thredds/catalog/meps25epsarchive/{today.year}/{today.month:02d}/{today.day:02d}/catalog.xml"
    file_url_base = f"https://thredds.met.no/thredds/dodsC/meps25epsarchive/{today.year}/{today.month:02d}/{today.day:02d}"
    # Get the datasets from the catalog
    catalog = TDSCatalog(catalog_url)
    datasets = [s for s in catalog.datasets if "meps_det_ml" in s]
    dataset_file_path = f"{file_url_base}/{sorted(datasets)[-1]}"
    
    return dataset_file_path


#%%
def load_meps_for_location(lat, lon, dataset_file_path=None, tol=0.1, altitude_min=0, altitude_max=3000):
    """
    dataset_file_path=None
    altitude_min=0
    altitude_max=3000
    """
    if dataset_file_path is None:
        dataset_file_path = find_latest_meps_file()

    dataset = xr.open_dataset(dataset_file_path, cache=True)

    # subset sogndal area:
    subset = dataset.sel(
        x=slice(dataset.x.quantile(0.265), dataset.x.quantile(0.28)), 
        y=slice(dataset.y.quantile(0.42), dataset.y.quantile(0.43))
    )

    subset.load()
```

**Comment by simeneide** [comment]
A second question: How can I find the (model) altitude of each grid point? I think for the cross-sectional files I could determine this by looking at nan values: "air_temperature_ml" would be nan for values below surface, whereas for this model output it seems to fill all altitude layers.

**Comment by joewkr** [comment]
> A second question: How can I find the (model) altitude of each grid point? I think for the cross-sectional files I could determine this by looking at nan values: "air_temperature_ml" would be nan for values below surface, whereas for this model output it seems to fill all altitude layers.

If you want to get the elevation of the model surface, it can be retrieved from the `surface_geopotential` variable. And if you meant the actual height of the model levels above the model surface, please consult with the following section of the Wiki: https://github.com/metno/NWPdocs/wiki/Examples#calculating-model-level-height

**Comment by simeneide** [comment]
Thanks! I still have the problem of loading data tho. Ive tried to use the coordinate system and data url system in case loading all and then filtering caused some expensive computation among files, but I get the same problem. The code below takes 13 minutes to run. It is 9MB(!) and Im on a stable fiber internet connection. Any ideas here? :) Or are these files not really meant for this kind of retrieval?

```
    path = 'https://thredds.met.no/thredds/dodsC/meps25epsarchive/2024/05/11/meps_det_ml_20240511T03Z.ncml?x[251:1:265],y[449:1:459],time[0:1:66],hybrid[0:1:64],height[0:1:0],longitude[449:1:459][251:1:265],latitude[449:1:459][251:1:265],air_temperature_ml[0:1:66][0:1:64][449:1:459][251:1:265],ap[0:1:64],b[0:1:64],surface_air_pressure[0:1:66][0:1:0][449:1:459][251:1:265],x_wind_ml[0:1:66][0:1:64][449:1:459][251:1:265],y_wind_ml[0:1:66][0:1:64][449:1:459][251:1:265]'
    dataset_raw = xr.open_dataset(path, cache=True)#, engine="netcdf4", chunks="auto")
    dataset_raw.load()
```

**Comment by joewkr** [comment]
I believe that files in the MEPS archive have almost the worst possible chunking for your application (i.e. extracting all levels and lead times for a small area) since `*_ml` fields are arranged as full 2D slices per model-level/output-time-step (`air_temperature_ml:_ChunkSizes = 1, 1, 1069, 949 ;`, for example). So, even if you extract a small region the full 4D array would have to be read from the filesystem which takes time. I'm not sure it is straightforward to solve this issue. Well, I'd suggest reducing, if possible, the size of the retrieved region along the dimensions with the chunk sizes of 1. So, `hybrid` would be the first candidate since I guess you don't actually need all the model levels up to 10hPa.

**Comment by simeneide** [comment]
A bite late reply, but thanks alot for the feedback! I understand the limits and possibilities here now. i guess the proper way to go is to build a separate data processing job for this. just a bit more "worklike" than I want for my hobby projects :)
